version: 1
disable_existing_loggers: true


formatters:
    standard:
        format: "%(asctime)s - %(module)s - %(name)s - %(levelname)s: %(message)s"
    error:
        format: "%(asctime)s - %(module)s - %(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: standard
        stream: ext://sys.stdout

    general_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: standard
        filename: /var/log/kqueen-api/kqueen_api.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: error
        filename: /var/log/kqueen-api/kqueen_api_error.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

root:
    level: NOTSET
    handlers: [console]
    propogate: yes

loggers:
    kqueen_api:
        level: INFO
        handlers: [error_file_handler, general_file_handler]
        propogate: yes
